apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hw-event-proxy
  namespace: "{{ .Namespace }}"
spec:
  to:
    kind: Service
    name: hw-event-proxy-service
  tls:
    termination: edge